/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/mDtg1x1Ox8O
 */
import { Input } from "@/components/ui/input"
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/ui/table"

export function Component() {
  return (
    (<div className="flex flex-col w-full min-h-screen">
      <div className="flex h-14 items-center border-b px-4">
        <form className="w-full">
          <div className="relative">
            <SearchIcon
              className="absolute left-2.5 top-2.5 h-4 w-4 text-gray-500 dark:text-gray-400" />
            <Input
              className="w-full bg-white shadow-none appearance-none pl-8 dark:bg-gray-950"
              placeholder="Search chapters..."
              type="search" />
          </div>
        </form>
      </div>
      <div className="flex-1 overflow-auto p-4">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Chapter</TableHead>
              <TableHead>URL</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            <TableRow>
              <TableCell>Introduction</TableCell>
              <TableCell>example.com/intro</TableCell>
            </TableRow>
            <TableRow>
              <TableCell>Chapter 1</TableCell>
              <TableCell>example.com/chapter1</TableCell>
            </TableRow>
            <TableRow>
              <TableCell>Chapter 2</TableCell>
              <TableCell>example.com/chapter2</TableCell>
            </TableRow>
            <TableRow>
              <TableCell>Conclusion</TableCell>
              <TableCell>example.com/conclusion</TableCell>
            </TableRow>
          </TableBody>
        </Table>
      </div>
    </div>)
  );
}


function SearchIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>)
  );
}
